---
documentclass: report
output: 
  pdf_document:
    template: "C:/Users/Lorenzo Costa/Desktop/Trabalhos/Economia Monetária/multiplicadorpt2/template/multiplicador.tex"
    keep_tex: TRUE
    pandoc_args: ["C:/Users/Lorenzo Costa/Desktop/Trabalhos/Economia Monetária/multiplicadorpt2/filter/crossref.lua"]
    includes:
      in_header: "C:/Users/Lorenzo Costa/Desktop/Trabalhos/Economia Monetária/multiplicadorpt2/header/header.tex"
classoption: secnumdepth=-1
---


```{r include=FALSE, message=FALSE, warning=FALSE}
library(GetBCBData)
library(dplyr)
library(pandoc)
library(ggplot2)
library(tibble)
library(tidyr)
library(kableExtra)
library(flextable)
library(openxlsx)
```


O multiplicador monetário é um valor, normalmente entre 1 e 2, no qual espera-se que os meios de pagamento da economia multiple e varie em relação à base monetária. Essa essa variável monetária é função de outras duas, o coeficiente "e" e o coeficiente "d", e, por isso, condiz com essa fórmula: $\alpha = \frac{1}{1-d(1-e)}$ . O "e" é uma razão entre os encaixes totais e os depósitos à vista dos bancos comerciais. O fato de haver os encaixes totais na fração torna o Banco Central (BACEN) influenciador direto desse coeficiente, visto que o valor de encaixes compulsórios está intrínseco aos encaixes totais. Portanto, o BACEN tem o poder de decidir o quanto vai ser passado da reserva dos bancos comerciais para o mesmo, o que significa que o "e" tem caráter negativo no multiplicador, pois sabe-se que ao aumentar esse encaixe, os bancos comerciais tenderão a oferecer menos empréstimos. Já o coeficiente "d" é a razão entre os depósitos à vista dos bancos comerciais e os meios de pagamento. Essa fração nada mais indica o quão ativos estão os bancos comerciais e em que proporção oferecem empréstimos e crétidos em relação aos meios de pagamentos totais da economia (PPMP + DV\textsubscript{bc}). Dessa forma, o "d" é um indicador da atuação dos bancos comerciais, e tem relação direta com o multiplicador.

Nos anos de 2003 à 2023, o multiplicador do banco central obteve uma média geral de 1,4262, o coeficiente "e" apresentou 0,4658 e o coeficiente "d", por sua vez, mostrou 0,5555 de média geral. Apartir da tabela e dos gráficos é possível observar que os picos do coeficiente "e" estão em 2003, nos meses de abril e julho, onde constaram respectivamente 0,650 e 0,648. É possível associar essa extremidade com as baixas expressivas do multiplicador monetário também em abril de 2003, com um valor de 1,281 e em julho com 1,283. No outro lado da moeda, houve uma grande queda no valor de "d" nos períodos de dezembro de 2015 e janeiro de 2016, 2017, 2018 e 2019 em que o coeficiente chegou a expressar os números de 0,466; 0,468; 0,465; 0,464 e 0,463 respectivamente, e como reflexo, o multiplicador teve uma de suas quedas mais agressivas do vintênio no meses de 2017, apontando valores de 1,242; 1.244; 1.253 etc, enquanto nesse momento, o coeficiente de "e" estava em níveis relativamente elevados, corroborando para o declínio do multiplicador. 

\subsubsection*{Segunda Análise - Os Efeitos da Copa do Mundo}

Para que a copa do mundo, sediada no Brasil em 2014, ocorresse com êxito, o governo procurou despender boa quantia de dinheiro para infraestrutura e urbanização. Um exemplo claro foi em 2010, momento em que foi anunciada o local da próxima copa, quando o BNDS (Banco Nacional de Desenvolvimento) criou o projeto "ProCopa" em que deferiu empréstimos e investimentos para a construção de novos estádios, reformas de arenas e urbanização em seu entorno. Nesse momento, do início em 2010 até julho 2014, onde a copa é encerrada, o multiplicador monetário encontrou uma média de 1,42, bem similar à média geral. É possível perceber também que houve uma queda brusca no meio do período de análise, porém logo se recupera com pequenos picos e consagra a média. Ao analisar a tragetória do coeficiente "d", é visível que vem em queda desde 2010 e que continua na decrescente até depois de 2015, enquanto o coeficiente "e" tem bastante crescentes no período de análise. Uma hipótese para o caso é de que, com os gastos governamentais em excesso, e bastante criação de demanda agregada, o BACEN, monopolizador da política monetária, preveu um possível aumento da inflação com essa distribuição de renda e com a renda vinda de fora por parte dos imigrantes no momento de copa do mundo, e por isso, os valores de "e" apresentam aumentos antes do ano da copa. Como os encaixes compulsórios estão se elevando, os bancos comerciais pretendem aplicar políticas contracionistas de empréstimos ou ao menos estagnar a concessão de crédito, e consequentemente o multiplicador apresenta algumas quedas antes de 2014, assim como procura manter um nível comum, mas cede em certos momentos já no ano da copa do mundo e das eleições presidenciais. 

