---
title: "Gráficos e Tabelas do Multiplicador"
author: "Lorenzo Costa Miranda"
date: "2024-03-24"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 4
---


```{r include=FALSE, message=FALSE, warning=FALSE}
library(zoo)
library(plotly)
library(htmltools)
library(GetBCBData)
library(dplyr)
library(pandoc)
library(ggplot2)
library(tibble)
library(tidyr)
library(kableExtra)
library(flextable)
library(openxlsx)
library(scales)
library(reshape2)
library(patchwork)
library(corrplot)
```

```{r include=FALSE, message=FALSE, warning=FALSE}
##Pegando os dados necessários pelo ID 


#reservas bancárias =/ Encaixes Totais
TabelaResBan <- GetBCBData::gbcbd_get_series(
  id =  1787,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#Papel Moeda no Poder Público

TabelaPMPP <- GetBCBData::gbcbd_get_series(
  id = 27789 ,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)


#Base monetária

TabelaBASE <- GetBCBData::gbcbd_get_series(
  id =  1788,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)


#Depósitos à vista
TabelaDepAvi <- GetBCBData::gbcbd_get_series(
 id =  27790,
 first.date = "2003-01-01",
 last.date = "2023-12-01"
)

#Meios de pagamento = PMPP + DV (TOTAL DE M1)
TabelaMP <- GetBCBData::gbcbd_get_series(
  id = 27791,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M1
TabelaM1 <- GetBCBData::gbcbd_get_series(
  id = 27791,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M2
TabelaM2 <- GetBCBData::gbcbd_get_series(
  id = 27810,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M3
TabelaM3 <- GetBCBData::gbcbd_get_series(
  id = 27813,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M4
TabelaM4 <- GetBCBData::gbcbd_get_series(
  id = 27815,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#IPCA
TabelaIPCA <- GetBCBData::gbcbd_get_series(
  id = 433,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#Taxa Selic

TabelaSELIC <- GetBCBData::gbcbd_get_series(
  id = 4189,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)


#Criando data para o período específico de análise

dates_impc <- seq.Date(from = as.Date("2015-06-01"), to = as.Date("2016-05-01"), by = "month")
dates_ano <- sequencia_datas <- seq(as.Date("2003-01-01"), as.Date("2023-12-31"), by = "years")


#Puxando os dados PIB projeção

Tabelaproj <- GetBCBData::gbcbd_get_series(
  id = 4380,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)


#Puxando a Tabela de PIB anual e tratando-a

dados_pib <- read.xlsx("C:/Users/Lorenzo Costa/Desktop/Trabalhos/Economia Monetaria/multiplicadorpt2/tabelaPIB.xlsx", sheet = "Tabela")

anos <- seq(2003,2021, by = 1)
print(anos, max.print = Inf)

vetorPIB <- as.numeric(dados_pib[4, -1])
print(vetorPIB, max.print = Inf)

vetor_PIB <-format(vetorPIB, big.mark = ".", decimal.mark = ",", scientific = FALSE)


TabelaPIB <- tibble(Data = anos, "PIB valores correntes(milhões)" = vetor_PIB)

TabelaPIB$`PIB valores correntes(milhões)` <- as.numeric(gsub("\\.", "", TabelaPIB$`PIB valores correntes(milhões)`))


diffPIB <- diff(TabelaPIB$`PIB valores correntes(milhões)`)
porcentoPIB <- (diffPIB / head(TabelaPIB$`PIB valores correntes(milhões)`, -1)) * 100
PIBvari <- c(NA, porcentoPIB)

TabelaPIB <- TabelaPIB %>%
  add_column("Variação Percentual (%)" = PIBvari, .after = "PIB valores correntes(milhões)")


#Repetir para que o PIB volte a ser numérico novamente


```

```{r echo = FALSE, message=FALSE, warning=FALSE}

### Criando um vetor para ser a coluna de tempo
dates <- seq.Date(from = as.Date("2003-01-01"), to = as.Date("2023-12-01"), by = "month")


#criando vetores das tabelas (não terá o vetor PIB - ja foi criado anteriormente)
vetormp <- TabelaMP[[2]]
vetordepavi <- TabelaDepAvi[[2]]
vetorresban <- TabelaResBan[[2]]
vetorPPMP <- TabelaPMPP[[2]]
vetorBASE <- TabelaBASE[[2]]
vetorM1 <- TabelaM1[[2]]
vetorM2 <- TabelaM2[[2]]
vetorM3 <- TabelaM3[[2]]
vetorM4 <- TabelaM4[[2]]
vetorIPCA <- TabelaIPCA[[2]]
vetorproj <- Tabelaproj[[2]]
vetorSELIC <- TabelaSELIC[[2]]

#formatando os vetores

vetor_mp <- format(vetormp, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_depavi <- format(vetordepavi, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_resban <- format(vetorresban, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_PPMP <- format(vetorPPMP, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_BASE <- format(vetorBASE, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M1 <- format(vetorM1, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M2 <- format(vetorM2, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M3 <- format(vetorM3, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M4 <- format(vetorM4, big.mark = ".", decimal.mark = ",", scientific = FALSE)

```

<br><br>


```{r echo = FALSE, message = FALSE, warning = FALSE}
#Criando a tibble dos Agregados Monetários, IPCA e PIB, mas só futuramente será exibida no arquivo html

TabelaAgregados <- tibble( Data = dates, "M1" = vetor_M1, "M2" = vetor_M2, "M3" = vetor_M3,
                           "M4" = vetor_M4, "PIB projeção" = vetorproj, "IPCA" = vetorIPCA, "SELIC" = vetorSELIC)


###Criação das estatísticas TabelaCoeficientes
#summary(TabelaCoeficientes)
#sapply(TabelaCoeficientes, sd)

vetorestat <- c("Max", "Min", "Mean", "sd")

vetorestatVARI <- c("Max", "Min", "Mean", "sd", "HighestVariance(%)", "LowestVariance(%)")


```
<br><br>

### Tabela dos Agregados Monetários, Taxa Selic e PIB

```{r echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
kable(TabelaAgregados, format = "html", longtable = TRUE, booktabs = TRUE, caption = "Valores dos Agregados e Selic") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))


```

<br><br>


```{r echo = FALSE, message = FALSE, warning = FALSE}
#str(TabelaAgregados$M1)
#sapply(TabelaAgregados, class)



# retirando os "." para milhares e reformatando para voltarem a ser variáveis numéricas. IPCA e SELIC já vieram com
#separadores de decimais e já são consideradas numerics naturalmente, então não precisa. 

TabelaAgregados$M1 <- as.numeric(gsub("\\.", "", TabelaAgregados$M1))
TabelaAgregados$M2 <- as.numeric(gsub("\\.", "", TabelaAgregados$M2))
TabelaAgregados$M3 <- as.numeric(gsub("\\.", "", TabelaAgregados$M3))
TabelaAgregados$M4 <- as.numeric(gsub("\\.", "", TabelaAgregados$M4))
TabelaPIB$`PIB valores correntes(milhões)` <- as.numeric(gsub("\\.", "", TabelaPIB$`PIB valores correntes(milhões)`))
#

```
#### Variação Percentual dos Agregados

```{r echo = FALSE, message = FALSE, warning = FALSE}

#Criação das variações no tempo dos agregados

diffM1 <- diff(TabelaAgregados$M1)
percentoM1 <- (diffM1 / head(TabelaAgregados$M1, -1)) * 100
M1vari <- c(NA, percentoM1)

diffM2 <- diff(TabelaAgregados$M2)
percentoM2 <- (diffM2 / head(TabelaAgregados$M2, -1)) * 100
M2vari <- c(NA, percentoM2)

diffM3 <- diff(TabelaAgregados$M3)
percentoM3 <- (diffM3 / head(TabelaAgregados$M3, -1)) * 100
M3vari <- c(NA, percentoM3)

diffM4 <- diff(TabelaAgregados$M4)
percentoM4 <- (diffM4 / head(TabelaAgregados$M4, -1)) * 100
M4vari <- c(NA, percentoM4)

diffIPCA <- diff(TabelaAgregados$IPCA)
percentoIPCA <- (diffIPCA / head(TabelaAgregados$IPCA, -1)) * 100
IPCAvari <- c(NA, percentoIPCA)

diffSELIC <- diff(TabelaAgregados$SELIC)
percentoSELIC <- (diffSELIC / head(TabelaAgregados$SELIC, -1)) * 100
SELICvari <- c(NA, percentoSELIC)

diffproj <- diff(TabelaAgregados$`PIB projeção`)
percentoproj <- (diffproj / head(TabelaAgregados$`PIB projeção`, -1)) *100
projvari <- c(NA, percentoproj)

#Criação da Tabela das variações percentuais

VariacoesPercentuais <- tibble(Data = dates, "M1 (%)" = M1vari, "M2 (%)" = M2vari, "M3 (%)" = M3vari, "M4 (%)" = M4vari,
                              "PIB (%)" = projvari, "IPCA (%)" = IPCAvari, "SELIC (%)" = SELICvari)



#Criação da Tabela em HTML

kable(VariacoesPercentuais, format = "html", booktabs = TRUE) %>%
  kable_styling(bootstrap_options = c( "hover", "condensed", "stripped"))

```

#### Estatística dos Agregados Monetários

```{r echo = FALSE, message = FALSE, warning = FALSE}
#TabelaAgregados$SELIC <- as.numeric(sub(",", ".", gsub("\\.", "", TabelaAgregados$SELIC), fixed = TRUE))
#
#Criando a Tabela de estatística para A TabelaAgregados, que já são numéricos. (só é possível tirar essa estatística de valores numéricos)

#sapply(TabelaAgregados, class)

#summary(TabelaAgregados)
#sapply(TabelaAgregados, sd)
#summary(TabelaPIB)
#sapply(TabelaPIB, sd)

#max(VariacoesPercentuais$M1, na.rm = TRUE)
#max(VariacoesPercentuais$M2, na.rm = TRUE)
#max(VariacoesPercentuais$M3, na.rm = TRUE)
#max(VariacoesPercentuais$M4, na.rm = TRUE)
#max(TabelaPIB$`Variação Percentual`, na.rm = TRUE)
#max(TabelaAgregados$IPCA)
#min(VariacoesPercentuais$M1, na.rm = TRUE)
#min(VariacoesPercentuais$M2, na.rm = TRUE)
#min(VariacoesPercentuais$M3, na.rm = TRUE)
#min(VariacoesPercentuais$M4, na.rm = TRUE)
#min(TabelaPIB$`Variação Percentual`, na.rm = TRUE)
#min(TabelaAgregados$IPCA)

#min(VariacoesPercentuais$`IPCA (%)`[is.finite(VariacoesPercentuais$`IPCA (%)`)], na.rm = TRUE)

estatM1 <- c("653.420.212", "86.231.763", "311.848.406", "160.128.500", "22.87 (2007-12)", "-17.58 (2008-01)")
estatM2 <- c("5.913.356.669", "385.467.653", "2.066.000.000", "1.407.171.000", "6.36 (2007-12)", "-3.12 (2008-01)")
estatM3 <- c("10.857.133.543", "696.054.502", "4.239.000.000", "2.822.259.000", "5.73 (2010-01)", "-1.26 (2019-01)")
estatM4 <- c("11.948.284.621", "810.272.451", "4.616.000.000", "3.046.371.000", " 4.49 (2007-09)", "-0.87 (2019-01)")
estatPIB <- c("949003", "125711", "446063", "219.889,5", "13.42 (2004-03)", "-10,74 (2020-04)")
estatIPCA <- c("2.250 (2003-01)" , "-0.680 (2022-07)", "0.450", "0,3563829", "2400 (2014-08)" ,"-1350 (2005-07)")
estatSELIC <- c("26.32 (2003-03)", "1.90 (2020-12)", "11.44", "4.863212", "-17.53 (2020-05)", "24.15 (2021-05)")

TabelaEstatAg <- tibble(Estatística = vetorestatVARI, M1 = estatM1, M2 = estatM2, M3 = estatM3, M4 = estatM4,
                        "PIB(milhões)" = estatPIB, IPCA = estatIPCA, SELIC = estatSELIC)
kable(TabelaEstatAg, format = "html", longtable = TRUE, booktabs = TRUE) %>%
  kable_styling(bootstrap_options = c( "stripped", "hover", "condensed"), font_size = 12)

```

```{r, echo = FALSE, message = FALSE, warning = FALSE, results='hide'}

#Colocando os valores em decimais para fazer o cálculo da média móvel

#sapply(TabelaAgregados, class)
TabelaAgregados <- as.data.frame(TabelaAgregados)

  

#Fazendo a média móvel (12meses)
TabelaAgregados$rollmeanIPCA <- rollmean(TabelaAgregados$IPCA, 12, fill = NA, align = 'right')
TabelaAgregados$rollmeanSELIC <- rollmean(TabelaAgregados$SELIC, 12, fill = NA, align = 'right')

TabelaAgregados$rollmeanIPCA3 <- rollmean(TabelaAgregados$IPCA, 3, fill = NA, align = 'right')
TabelaAgregados$rollmeanSELIC3 <- rollmean(TabelaAgregados$SELIC, 3, fill = NA, align = 'right')



```  
  
```{r echo = FALSE, message = FALSE, warning = FALSE}  
  
#MANIPULANDO OS DADOS DO MULTIPLICADOR BANCÀRIO
  
#class(TabelaResBan$value)
#class(TabelaDepAvi$value)
#class(TabelaMP$value)
#class(TabelaBASE$value)
#class(TabelaPMPP$value)

#criando vetores para cada valor do MP, DV, ResBan, PPMP e BASE MONETARIA
vetormp <- TabelaMP[[2]]
vetordepavi <- TabelaDepAvi[[2]]
vetorresban <- TabelaResBan[[2]]
vetorPPMP <- TabelaPMPP[[2]]
vetorBASE <- TabelaBASE[[2]]


#formatando os vetores

vetor_mp <- format(vetormp, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_depavi <- format(vetordepavi, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_resban <- format(vetorresban, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_PPMP <- format(vetorPPMP, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_BASE <- format(vetorBASE, big.mark = ".", decimal.mark = ",", scientific = FALSE)
  
#criação das séries temporais

###SABEMOS QUE B = PMPP + ENCAIXES TOTAIS / LOGO ENCAIXES TOTAIS = B - PMPP

#Função de subtração

Z <- function(s, t){
      Resultado = s - t
      return(Resultado)
}


#criando um vetor com os encaixes técnicos

VetorEncaixe <- mapply(Z, TabelaBASE[[2]], TabelaPMPP[[2]])

#Tabela do vetor de encaxe

TabelaEncaixe <- tibble(Data = dates, Valor = VetorEncaixe)

#Formatando o vetor_encaixe

Vetor_Encaixe <- format(VetorEncaixe, big.mark = ".", decimal.mark = ",", scientific = FALSE)


### juntando todas as variáveis em uma tabela só

TabelaBacen <- tibble(Data = dates, "Meios de Pagamentos" = vetor_mp, 
            "Depositos a vista" = vetor_depavi, "Encaixes Totais" = Vetor_Encaixe)




# Criando função para realizar o cálculo do coeficiente
X <- function(x,y){
  Resultado = x/y
  return(Resultado)
}



Coeficiente_e <- mapply(X, TabelaEncaixe[[2]], TabelaDepAvi[[2]])

Coeficiente_d <- mapply(X, TabelaDepAvi[,2], TabelaMP[,2])


SerieTemporal_e <- tibble(data = dates, valor = Coeficiente_e)
SerieTemporal_d <- tibble(data = dates, valor = Coeficiente_d)

y <- function(d,e){
  Resultado = 1/(1-d * (1-e))
  return(Resultado)
}

Coeficientes <- tibble(data = dates, Valor_de_e = Coeficiente_e, Valor_de_d = Coeficiente_d)


Multiplicador_mon <- mapply(y, Coeficientes[,3], Coeficientes[,2])
SerieTemporal_alpha <- tibble(data = dates, valor = Multiplicador_mon)
  

MultiAnos <- SerieTemporal_alpha %>%
  mutate(ano = lubridate::year(data)) %>%
  group_by(ano) %>%
  summarize(media_alpha = mean(valor))

diff_multi <- diff(SerieTemporal_alpha$valor)
percento_multi <- (diff_multi / head(SerieTemporal_alpha$valor, -1)) *100
multi_vari <- c(NA, percento_multi)

diff_multiano <- diff(MultiAnos$media_alpha)
percento_multiano <- (diff_multiano / head(MultiAnos$media_alpha, -1)) *100
multi_variano <- c(NA, percento_multiano)

SerieTemporal_alpha <- SerieTemporal_alpha %>%
  add_column("Variacao multi" = multi_vari, .after = 'valor')

MultiAnos <- MultiAnos %>%
  add_column("Variacao ano multi" = multi_variano, .after = 'media_alpha')


impcmulti <- SerieTemporal_alpha %>%
  slice(150:161)


```  
  
<br><br>


#### Gráficos dos Agregados Monetários, Taxa Selic e PIB


```{r echo = FALSE, message = FALSE, warning=FALSE}

ggplot(data = TabelaAgregados) +
  geom_line(aes( x = Data, y = rollmeanIPCA, color = "rollmeanIPCA")) +
  geom_line(aes( x = Data, y = IPCA, color = "IPCA")) +
  labs(x = "Data", y = "Valores", title = "Média Móvel de 12 meses do IPCA") +
  scale_color_manual(values = c("rollmeanIPCA" = "purple2", "IPCA" = "pink")) +
  theme_minimal()


#colors()
```
<br><br>



```{r echo = FALSE, message = FALSE, warning = FALSE, fig.cap = "Plot Série Temporal dos Agregados Monetários"}
# Gráfico conjunto dos agregados monetários
#colors()

ggplot(data = TabelaAgregados, aes(x = Data, y = M1, color = "M1")) +
  geom_line() +
  geom_line(aes(y = M2, color = "M2")) +
  geom_line(aes(y = M3, color = "M3")) +
  geom_line(aes(y = M4, color = "M4")) +
  labs(x = "Data", y = "Valores", title = "Série Temporal dos Agregados Monetários") +
  scale_color_manual(values = c("M1" = "green", "M2" = "lawngreen", "M3" = "yellow", "M4" = "orange")) +
  scale_y_continuous(labels = label_number(big.mark = ".", decimal.mark = ",")) +
  theme_minimal()
      

```

<br><br>

```{r echo = FALSE, message = FALSE, warning = FALSE}

ImpcAgre <- TabelaAgregados %>%
  slice(150:161)

#Eu estava utilizando esse código pois estava usando outro dataframe para o PIB que foi retirada de uma tabela de excel
#Essa tabela estava com o PIB em anos, mas agora está sendo adotada o PIB em meses, porém é apenas a projeção.
impcPib <- TabelaAgregados %>%
  slice(150:161)


```


```{r echo = FALSE, message = FALSE, warning = FALSE}



diff_M1 <- diff(ImpcAgre$M1)
percento_M1 <- (diff_M1 / head(ImpcAgre$M1, -1)) * 100
M1_vari <- c(NA, percento_M1)

diff_M2 <- diff(ImpcAgre$M2)
percento_M2 <- (diff_M2 / head(ImpcAgre$M2, -1)) * 100
M2_vari <- c(NA, percento_M2)

diff_M3 <- diff(ImpcAgre$M3)
percento_M3 <- (diff_M3 / head(ImpcAgre$M3, -1)) * 100
M3_vari <- c(NA, percento_M3)

diff_M4 <- diff(ImpcAgre$M4)
percento_M4 <- (diff_M4 / head(ImpcAgre$M4, -1)) * 100
M4_vari <- c(NA, percento_M4)

diff_IPCA <- diff(ImpcAgre$IPCA)
percento_IPCA <- (diff_IPCA / head(ImpcAgre$IPCA, -1)) * 100
IPCA_vari <- c(NA, percento_IPCA)

diff_SELIC <- diff(ImpcAgre$SELIC)
percento_SELIC <- (diff_SELIC / head(ImpcAgre$SELIC, -1)) * 100
SELIC_vari <- c(NA, percento_SELIC)

diff_proj <- diff(ImpcAgre$`PIB projeção`)
percento_proj <- (diff_proj / head(ImpcAgre$`PIB projeção`, -1)) * 100
proj_vari <- c(NA, percento_proj)

Variacoes_Percentuais <- tibble(Data = dates_impc, "M1 (%)" = M1_vari, "M2 (%)" = M2_vari, "M3 (%)" = M3_vari, "M4 (%)" = M4_vari, "PIB (%)" = proj_vari, "IPCA (%)" = IPCA_vari, "SELIC (%)" = SELIC_vari)


VariacoesPercentuais1 <- VariacoesPercentuais[-1, ]
VariacoesPercentuais1$`IPCA (%)`[90] <- 0
VariacoesPercentuais12 <- VariacoesPercentuais1[is.finite(VariacoesPercentuais1$`IPCA (%)`), ]


```

```{r echo = FALSE, message = FALSE, warning = FALSE, fig.width=14, fig.height=12, out.width='100%'}



# criando multiplos ggplots
# Formatando os próximos plots para saírem embutidos:
par(mfrow = c(2, 2), oma = c(0, 0, 6, 0))



#Criando uma gráfico plot com M1 e SELIC

plot(TabelaAgregados$Data, TabelaAgregados$M1, type = "l",
     col = "green", ylim = c(min(TabelaAgregados$M1),
                             max(TabelaAgregados$M1)),
     ylab = "M1", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)

#sobrepondo esse gráfico com outro plot para a taxa selic

par(new = TRUE)
plot(TabelaAgregados$Data, TabelaAgregados$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(TabelaAgregados$SELIC),
              max(TabelaAgregados$SELIC)))

#Criando um segundo eixo y para a taxa selic
axis(side = 4, at = pretty(range(TabelaAgregados$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)



### Fazendo o mesmo para M2 e SELIC

plot(TabelaAgregados$Data, TabelaAgregados$M2, type = "l",
    col = "lawngreen", ylim = c(min(TabelaAgregados$M2),
                                max(TabelaAgregados$M2)),
    ylab = "M2", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)
par(new = TRUE)
plot(TabelaAgregados$Data, TabelaAgregados$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(TabelaAgregados$SELIC),
              max(TabelaAgregados$SELIC)))
axis(side =  4, at = pretty(range(TabelaAgregados$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)

# Fazendo o mesmo para M3 e SELIC

plot(TabelaAgregados$Data, TabelaAgregados$M3, type = "l",
     col = "yellow", ylim = c(min(TabelaAgregados$M3),
                              max(TabelaAgregados$M3)),
     ylab = "M3", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)
par(new = TRUE)
plot(TabelaAgregados$Data, TabelaAgregados$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(TabelaAgregados$SELIC),
              max(TabelaAgregados$SELIC)))
axis(side =  4, at = pretty(range(TabelaAgregados$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)

# Fazendo o mesmo para M4 e SELIC

plot(TabelaAgregados$Data, TabelaAgregados$M4, type = "l",
     col = "orange", ylim = c(min(TabelaAgregados$M4),
                              max(TabelaAgregados$M4)),
     ylab = "M4", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)
par(new = TRUE)
plot(TabelaAgregados$Data, TabelaAgregados$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(TabelaAgregados$SELIC),
              max(TabelaAgregados$SELIC)))
axis(side =  4, at = pretty(range(TabelaAgregados$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)

par(mfrow = c(1,1))

mtext("Comparação Entre os Agregados e a Selic", outer = TRUE, cex = 1.5, line = 2)

```
<br><br>

<br><br>

```{r echo = FALSE, message = FALSE, warning = FALSE}

## Importante, e mudança de IDEIA!! Agora toda a análise geral será feita em anos, e não meses. Só será em meses na
#O PIB em projeção mensal também será agregado em anos
# Análise específica

TabelaAnos <- TabelaAgregados %>%
  mutate(ano = lubridate::year(Data)) %>%
  group_by(ano) %>%
  summarize(media_m1 = mean(M1),
            media_m2 = mean(M2),
            media_m3 = mean(M3),
            media_m4 = mean(M4),
            media_proj = mean(`PIB projeção`),
            media_selic = mean(SELIC),
            media_ipca = mean(IPCA))
      

#Realizando agora a variação anual das médias anuais que utilzaram os valores mensais.

diff_selicano <- diff(TabelaAnos$media_selic)
percento_selicano <- (diff_selicano / head(TabelaAnos$media_selic, -1)) * 100
selicano_vari <- c(NA, percento_selicano)

diff_ipcaano <- diff(TabelaAnos$media_ipca)
percento_ipcaano <- (diff_ipcaano / head(TabelaAnos$media_ipca, -1)) * 100
ipcaano_vari <- c(NA, percento_ipcaano)

diff_m1ano <- diff(TabelaAnos$media_m1)
percento_m1ano <- (diff_m1ano / head(TabelaAnos$media_m1, -1)) * 100
m1ano_vari <- c(NA, percento_m1ano)

diff_m2ano <- diff(TabelaAnos$media_m2)
percento_m2ano <- (diff_m2ano / head(TabelaAnos$media_m2, -1)) * 100
m2ano_vari <- c(NA, percento_m2ano)

diff_m3ano <- diff(TabelaAnos$media_m3)
percento_m3ano <- (diff_m3ano / head(TabelaAnos$media_m3, -1)) * 100
m3ano_vari <- c(NA, percento_m3ano)

diff_m4ano <- diff(TabelaAnos$media_m4)
percento_m4ano <- (diff_m4ano / head(TabelaAnos$media_m4, -1)) * 100
m4ano_vari <- c(NA, percento_m4ano)

diff_projano <- diff(TabelaAnos$`PIB projeção`)
percento_projano <- (diff_projano / head(TabelaAnos$media_proj, -1)) * 100
projano_vari <- c(NA, percento_projano)

TabelaAnos <- TabelaAnos %>%
  add_column("Variacao Percentual Selic" = selicano_vari, "Variacao Percentual Ipca" = ipcaano_vari,
             "Variacao Percentual M1" = m1ano_vari, "Variacao Percentual M2" = m2ano_vari,
             "Variacao Percentual PIB" = projano_vari, "Variacao Percentual M3" = m3ano_vari, 
             "Variacao Percentual M4" = m4ano_vari, .after = "media_selic")

#view(TabelaAnos)

p99 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M1`, name = "M1 (%)", color = I("green")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Selic`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p99 <- p99 %>%
  layout(
    title = "M1 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M1"),
    yaxis2 = list(
      title = "SELIC",
      overlaying = "y",
      side = "right"
    )
  )

p99

#Fazendo o mesmo para M2 e IPCA

p98 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M2`, name = "M2 (%)", color = I("lawngreen")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Selic`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p98 <- p98 %>%
  layout(
    title = "M2 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M2"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p98

# Fazendo o mesmo para M3 e IPCA


p97 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M3`, name = "M3 (%)", color = I("yellow")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Selic`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p97 <- p97 %>%
  layout(
    title = "M3 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M3"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p97

# Fazendo o mesmo para M4 e IPCA



p96 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M4`, name = "M4 (%)", color = I("orange")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Selic`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p96 <- p96 %>%
  layout(
    title = "M4 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M4"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p96

```
<br><br>

<br><br>


```{r echo = FALSE, message=FALSE, warning=FALSE, fig.width=4, fig.height=4, out.width='100%'}
#Criando Tabela de Correlação entre os Agregados monetários e a Taxa Selic

#sapply(TabelaPIB, class)

#  add_lines(data = TabelaAgregados, x = ~Data, y = ~IPCA, name = "IPCA", color = I("pink"),
            #yaxis = "y2")


#Criando uma gráfico plotly com M1 e IPCA 

p4 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M1`, name = "M1 (%)", color = I("green")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Ipca`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p4 <- p4 %>%
  layout(
    title = "M1 em relação ao IPCA",
    yaxis = list(title = "M1"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p4

# Fazendo o mesmo para M2 e IPCA

p3 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M2`, name = "M2 (%)", color = I("lawngreen")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Ipca`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p3<- p3 %>%
  layout(
    title = "M2 em relação ao IPCA",
    yaxis = list(title = "M2"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p3

# Fazendo o mesmo para M3 e IPCA


p2 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M3`, name = "M3 (%)", color = I("yellow")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Ipca`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p2 <- p2 %>%
  layout(
    title = "M3 em relação ao IPCA",
    yaxis = list(title = "M3"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p2

# Fazendo o mesmo para M4 e IPCA



p1 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M4`, name = "M4 (%)", color = I("orange")) %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual Ipca`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p1 <- p1 %>%
  layout(
    title = "M4 em relação ao IPCA",
    yaxis = list(title = "M4"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p1


```
<br><br>


```{r echo = FALSE, message = FALSE, warning = FALSE}

#Relação dos Agregados monetários com o multiplicador monetário dos 20 anos

p50 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M1`, name = "M1 (%)", color = I("lawngreen")) %>%
  add_lines(data = MultiAnos, x = ~ano, y = ~`Variacao ano multi`, name = "Multiplicador (%)", color = I("brown"))

p50 <- p50 %>%
  layout(
    title = "M1 em relação ao multiplicador",
    yaxis = list(title = "M1"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p50

p51 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M2`, name = "M2 (%)", color = I("green")) %>%
  add_lines(data = MultiAnos, x = ~ano, y = ~`Variacao ano multi`, name = "Multiplicador (%)", color = I("brown"))

p51 <- p51 %>%
  layout(
    title = "M2 em relação ao multiplicador",
    yaxis = list(title = "M2"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p51

p52 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M3`, name = "M3 (%)", color = I("yellow")) %>%
  add_lines(data = MultiAnos, x = ~ano, y = ~`Variacao ano multi`, name = "Multiplicador (%)", color = I("brown"))

p52 <- p52 %>%
  layout(
    title = "M3 em relação ao multiplicador",
    yaxis = list(title = "M3"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p52

p53 <- plot_ly() %>%
  add_lines(data = TabelaAnos, x = ~ano, y = ~`Variacao Percentual M4`, name = "M4 (%)", color = I("orange")) %>%
  add_lines(data = MultiAnos, x = ~ano, y = ~`Variacao ano multi`, name = "Multiplicador (%)", color = I("brown"))

p53 <- p53 %>%
  layout(
    title = "M4 em relação ao multiplicador",
    yaxis = list(title = "M4"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p53

```
<br><br>

```{r echo = FALSE, warning = FALSE, message = FALSE}


vecm1pib <- mapply(X, TabelaAnos[[2]], TabelaAnos[[6]])
vecm1pib <- vecm1pib / 1000000

vecm2pib <- mapply(X, TabelaAnos[[3]], TabelaAnos[[6]])
vecm2pib <- vecm2pib / 1000000

vecm3pib <- mapply(X, TabelaAnos[[4]], TabelaAnos[[6]])
vecm3pib <- vecm3pib / 1000000

vecm4pib <- mapply(X, TabelaAnos[[5]], TabelaAnos[[6]])
vecm4pib <- vecm4pib / 1000000

Anos <- seq(2003, 2023, by = 1)

tabeladiv <- tibble(Anos = Anos, "M1/PIB" = vecm1pib, "M2/PIB" = vecm2pib, "M3/PIB" = vecm3pib, "M4/PIB" = vecm4pib)

P20 <- plot_ly() %>%
  add_lines(data = tabeladiv, x = ~Anos, y = ~`M1/PIB`, name = "M1/PIB", color = I("lawngreen")) %>%
  add_lines(data = tabeladiv, x = ~Anos, y = ~`M2/PIB`, name = "M2/PIB", color = I("green")) %>%
  add_lines(data = tabeladiv, x = ~Anos, y = ~`M3/PIB`, name = "M3/PIB", color = I("yellow")) %>%
  add_lines(data = tabeladiv, x = ~Anos, y = ~`M4/PIB`, name = "M4/PIB", color = I("orange"))

P20 <- P20 %>%
  layout(
    title = "Relação dos Agregados Monetários com o PIB",
    yaxis = list(title = "Agregados Monetários (M1, M2, M3, M4)"),
      overlaying = "y",
      side = "right"
    )

P20


```

<br><br>

```{r, echo=FALSE, message=FALSE, warning=FALSE}

colnames(TabelaPIB)[colnames(TabelaPIB) == "PIB valores correntes(milhões)"] <- "PIB_Valores_Correntes_milhoes"


Plotpib <- plot_ly() %>%
    add_lines(data = TabelaAgregados, x = ~Data, y = ~M1, name = "M1", color = I("green")) %>%
  add_lines(data = TabelaAgregados, x = ~Data, y = ~M2, name = "M2", color = I("lawngreen")) %>%
  add_lines(data = TabelaAgregados, x = ~Data, y = ~M3, name = "M3", color = I("yellow")) %>%
  add_lines(data = TabelaAgregados, x = ~Data, y = ~M4, name = "M4", color = I("orange")) %>%
  add_lines(data = TabelaAgregados, x = ~Data, y = ~`PIB projeção`, name = "PIB R$ (milhões)", yaxis = "y2", color = I("darkblue"))

# Configuração do layout com múltiplos eixos Y
Plotpib <- Plotpib %>%
  layout(
    autosize = F, # Desativa o dimensionamento automático
    width = 800,  # Largura do gráfico em pixels
    height = 600, # Altura do gráfico em pixels
    margin = list(l = 50, r = 50, b = 100, t = 100, pad = 4),
    title = "PIB e os Agregados Monetários",
    yaxis = list(title = "Agregados Monetários (M1, M2, M3, M4)"),
    yaxis2 = list(
      title = "PIB",
      overlaying = "y",
      side = "right",
      anchor = "free",
      position = 1.00
    )
  )

# Renderização do gráfico
Plotpib
```

<br><br>

<br><br>


```{r echo=FALSE, message=FALSE, warning=FALSE}

#Para melhor visualização do gráfico, utilizei os dados do PIB real anual


p <- plot_ly() %>%
  add_lines(data = VariacoesPercentuais, x = ~Data, y = ~`SELIC (%)`, name = "SELIC", color = I("cyan")) %>%
  add_lines(data = TabelaPIB, x = ~Data, y = ~`Variação Percentual (%)`, name = "PIB",
            yaxis = 'y2', color = I("darkblue"))

p <- p %>%
  layout(
    title = "Gráfico do PIB em relação à SELIC",
    yaxis = list(title = "SELIC"),
    yaxis2 = list(
      title = "PIB Valores Correntes (milhões)",
      overlaying = "y",
      side = "right"
    )
  )

p


```


```{r echo = FALSE, message = FALSE, warning= FALSE}

p5 <- plot_ly() %>%
  add_lines(data = TabelaAgregados, x = ~Data, y = ~SELIC, name = "SELIC", color = I('cyan4')) %>%
  add_lines(data = TabelaAgregados, x = ~Data, y = ~IPCA, name = "IPCA", color = I('purple2'),
            yaxis = 'y2')

p5 <- p5 %>%
  layout(
    title = "Comparação entre o IPCA e da SELIC",
    yaxis = list(title = "SELIC"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p5



```

<br><br>
<br><br>

### Análise Específica

<br><br>

#### Estatística dos Agregados

<br><br>


```{r echo = FALSE, warning = FALSE, message=FALSE}

kable(Variacoes_Percentuais, format = "html", booktabs = TRUE) %>%
  kable_styling(bootstrap_options = c( "hover", "condensed", "stripped"))

```

<br><br>


```{r echo = FALSE, warning = FALSE, message = FALSE}

#summary(Variacoes_Percentuais)
#sapply(Variacoes_Percentuais, sd)

#summary(ImpcAgre)
#sapply(ImpcAgre, sd)


imp_m1 <- c("347.220.589", "308.941.546", "318.176.364", "10.231.260", "7.21 (2015-12)", "-7.40 (2016-01)")
imp_m2 <- c("2.334.143.094", "2.200.717.397", "2.269.000.000", "45.630.950", "2.84 (2015-12)", "-1.43 (2016-01)")
imp_m3 <- c("5.008.017.964", "4.563.586.143", "4.773.000.000", "162.332.800", "2.92 (2015-12)", "-0.53 (2016-01)")
imp_m4 <- c("5.453.699.716", "4.951.069.509", "5.211.000.000", "177.033.800", "2.88 (2015-12)", "-0.38 (2016-01)")
imp_PIB <- c("528139", "481694", "507281", "14.545,7", "7.68 (2016-03)", "-6.65 (2016-01)")
imp_IPCA <- c("1.27 (2016-01)", "0.2200 (2015-08)", "0.7458", "0,2821495", "145.45 (2015-09)", "-64.51 (2015-08)")
imp_SELIC <- c("14.15 (2015-08)", "13.58 (2015-06)", "14.06", "0,2018306", "3.36 (2015-08)", "0 (2015-09 à 2016-05)")



TabelaEstat_Ag <- tibble(Estatística = vetorestatVARI, M1 = imp_m1, M2 = imp_m2, M3 = imp_m3, M4 = imp_m4,
                        "PIB(milhões)" = imp_PIB, IPCA = imp_IPCA, SELIC = imp_SELIC)
kable(TabelaEstat_Ag, format = "html", longtable = TRUE, booktabs = TRUE) %>%
  kable_styling(bootstrap_options = c( "stripped", "hover", "condensed"), font_size = 12)

```

<br><br>

#### Gráficos

<br><br>

```{r echo = FALSE, message = FALSE, warning = FALSE}


Pipca <- plot_ly() %>%
  add_lines( data = ImpcAgre, x = ~Data, y = ~IPCA, name = "IPCA",
             color = I("pink"))

Pipca <- Pipca %>%
  layout(
    title = "Média Móvel de 3 Meses do IPCA no Período de Análise",
    yaxis = list(title = "Valores IPCA")
    )

Pipca


Pagremon1 <- plot_ly() %>%
  add_lines(data = ImpcAgre, x = ~Data, y = ~M1, name = "M1", color = I("green"))

Pagremon1 <- Pagremon1 %>%
   layout(
    title = "Série Temporal dos Agregados Monetários",
    yaxis = list(title = "Valores de M1")
    )

Pagremon1

Pagremon2 <- plot_ly() %>%
  add_lines(data = ImpcAgre, x = ~Data, y = ~M2, name = "M2", color = I("lawngreen")) 

Pagremon2 <- Pagremon2 %>%
   layout(
    title = "Série Temporal dos Agregados Monetários",
    yaxis = list(title = "Valores de M2")
    )

Pagremon2


Pagremon3 <- plot_ly() %>%
  add_lines(data = ImpcAgre, x = ~Data, y = ~M3, name = "M3", color = I("yellow"))


Pagremon3 <- Pagremon3 %>%
   layout(
    title = "Série Temporal dos Agregados Monetários",
    yaxis = list(title = "Valores de M3")
    )

Pagremon3

Pagremon4 <- plot_ly() %>%
  add_lines(data = ImpcAgre, x = ~Data, y = ~M4, name = "M4", color = I("orange"))

Pagremon4 <- Pagremon4 %>%
   layout(
    title = "Série Temporal dos Agregados Monetários",
    yaxis = list(title = "Valores de M4")
    )

Pagremon4



```

```{r echo = FALSE, message=FALSE, warning = FALSE, fig.width=14, fig.height=12, out.width='100%'}



# criando multiplos ggplots
# Formatando os próximos plots para saírem embutidos:
par(mfrow = c(2, 2), oma = c(0, 0, 6, 0))



#Criando uma gráfico plot com M1 e SELIC

plot(ImpcAgre$Data, ImpcAgre$M1, type = "l",
     col = "green", ylim = c(min(ImpcAgre$M1),
                             max(ImpcAgre$M1)),
     ylab = "M1", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)

#sobrepondo esse gráfico com outro plot para a taxa selic

par(new = TRUE)
plot(ImpcAgre$Data, ImpcAgre$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(ImpcAgre$SELIC),
              max(ImpcAgre$SELIC)))

#Criando um segundo eixo y para a taxa selic
axis(side = 4, at = pretty(range(ImpcAgre$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)



### Fazendo o mesmo para M2 e SELIC

plot(ImpcAgre$Data, ImpcAgre$M2, type = "l",
    col = "lawngreen", ylim = c(min(ImpcAgre$M2),
                                max(ImpcAgre$M2)),
    ylab = "M2", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)
par(new = TRUE)
plot(ImpcAgre$Data, ImpcAgre$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(ImpcAgre$SELIC),
              max(ImpcAgre$SELIC)))
axis(side =  4, at = pretty(range(ImpcAgre$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)

# Fazendo o mesmo para M3 e SELIC

plot(ImpcAgre$Data, ImpcAgre$M3, type = "l",
     col = "yellow", ylim = c(min(ImpcAgre$M3),
                              max(ImpcAgre$M3)),
     ylab = "M3", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)
par(new = TRUE)
plot(ImpcAgre$Data, ImpcAgre$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(ImpcAgre$SELIC),
              max(ImpcAgre$SELIC)))
axis(side =  4, at = pretty(range(ImpcAgre$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)

# Fazendo o mesmo para M4 e SELIC

plot(ImpcAgre$Data, ImpcAgre$M4, type = "l",
     col = "orange", ylim = c(min(ImpcAgre$M4),
                              max(ImpcAgre$M4)),
     ylab = "M4", xlab = "Data", cex.lab = 2.0, cex.axis = 1.5)
par(new = TRUE)
plot(ImpcAgre$Data, ImpcAgre$SELIC, type = "l",
     col = "cyan", axes = FALSE, xlab = "", ylab = "",
     ylim = c(min(ImpcAgre$SELIC),
              max(ImpcAgre$SELIC)))
axis(side =  4, at = pretty(range(ImpcAgre$SELIC)))
mtext("Taxa Selic (%)", side = 4, line = 3)

par(mfrow = c(1,1))

mtext("Comparação Entre os Agregados e a Selic", outer = TRUE, cex = 1.5, line = 2)


```

<br><br>

```{r echo = FALSE, message = FALSE, warning = FALSE}


#view(TabelaAnos)

p95 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M1 (%)`, name = "M1 (%)", color = I("green")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`SELIC (%)`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p95 <- p95 %>%
  layout(
    title = "M1 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M1"),
    yaxis2 = list(
      title = "SELIC",
      overlaying = "y",
      side = "right"
    )
  )

p95

#Fazendo o mesmo para M2 e IPCA

p94 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M2 (%)`, name = "M2 (%)", color = I("lawngreen")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`SELIC (%)`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p94 <- p94 %>%
  layout(
    title = "M2 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M2"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p94

# Fazendo o mesmo para M3 e IPCA


p93 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M3 (%)`, name = "M3 (%)", color = I("yellow")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`SELIC (%)`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p93 <- p93 %>%
  layout(
    title = "M3 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M3"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p93

# Fazendo o mesmo para M4 e IPCA



p92 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M4 (%)`, name = "M4 (%)", color = I("orange")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`SELIC (%)`, name = "SELIC (%)", color = I('cyan'),
            yaxis = "y2")

p92 <- p92 %>%
  layout(
    title = "M4 em relação à SELIC Agregados em Anos",
    yaxis = list(title = "M4"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p92

```


<br><br>




```{r echo = FALSE, message=FALSE, warning=FALSE, fig.width=4, fig.height=4, out.width='100%'}

#Criando uma gráfico plotly com M1 e IPCA 

p9 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M1 (%)`, name = "M1 (%)", color = I("green")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`IPCA (%)`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p9 <- p9 %>%
  layout(
    title = "M1 em relação ao IPCA",
    yaxis = list(title = "M1"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p9

# Fazendo o mesmo para M2 e IPCA

p6 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M2 (%)`, name = "M2 (%)", color = I("lawngreen")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`IPCA (%)`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p6 <- p6 %>%
  layout(
    title = "M2 em relação ao IPCA",
    yaxis = list(title = "M2"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p6

# Fazendo o mesmo para M3 e IPCA


p7 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M3 (%)`, name = "M3 (%)", color = I("yellow")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`IPCA (%)`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p7 <- p7 %>%
  layout(
    title = "M3 em relação ao IPCA",
    yaxis = list(title = "M3"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p7

# Fazendo o mesmo para M4 e IPCA



p8 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M4 (%)`, name = "M4 (%)", color = I("orange")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`IPCA (%)`, name = "IPCA (%)", color = I('purple2'),
            yaxis = "y2")

p8 <- p8 %>%
  layout(
    title = "M4 em relação ao IPCA",
    yaxis = list(title = "M4"),
    yaxis2 = list(
      title = "IPCA",
      overlaying = "y",
      side = "right"
    )
  )

p8

```

<br><br>


```{r echo = FALSE, message = FALSE, warning = FALSE}

#Relação dos Agregados monetários com o multiplicador monetário dos 20 anos

p54 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M1 (%)`, name = "M1 (%)", color = I("lawngreen")) %>%
  add_lines(data = impcmulti, x = ~data, y = ~`Variacao multi`, name = "Multiplicador (%)", color = I("brown"))

p54 <- p54 %>%
  layout(
    title = "M1 em relação ao multiplicador",
    yaxis = list(title = "M1"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p54

p55 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M2 (%)`, name = "M2 (%)", color = I("green")) %>%
  add_lines(data = impcmulti, x = ~data, y = ~`Variacao multi`, name = "Multiplicador (%)", color = I("brown"))

p55 <- p55 %>%
  layout(
    title = "M2 em relação ao multiplicador",
    yaxis = list(title = "M2"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p55

p56 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M3 (%)`, name = "M3 (%)", color = I("yellow")) %>%
  add_lines(data = impcmulti, x = ~data, y = ~`Variacao multi`, name = "Multiplicador (%)", color = I("brown"))

p56 <- p56 %>%
  layout(
    title = "M3 em relação ao multiplicador",
    yaxis = list(title = "M3"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p56

p57 <- plot_ly() %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`M4 (%)`, name = "M4 (%)", color = I("orange")) %>%
  add_lines(data = impcmulti, x = ~data, y = ~`Variacao multi`, name = "Multiplicador (%)", color = I("brown"))

p57 <- p57 %>%
  layout(
    title = "M4 em relação ao multiplicador",
    yaxis = list(title = "M4"),
    yaxis2 = list(
      title = "multiplicador",
      overlaying = "y",
      side = "right"
    )
  )

p57

```

<br><br>


```{r echo = FALSE, warning = FALSE, message = FALSE}


vecm1pib2 <- mapply(X, TabelaAgregados[[2]], TabelaAgregados[[6]])
vecm1pib2 <- vecm1pib2 / 1000000

vecm2pib2 <- mapply(X, TabelaAgregados[[3]], TabelaAgregados[[6]])
vecm2pib2 <- vecm2pib2 / 1000000

vecm3pib2 <- mapply(X, TabelaAgregados[[4]], TabelaAgregados[[6]])
vecm3pib2 <- vecm3pib2 / 1000000

vecm4pib2 <- mapply(X, TabelaAgregados[[5]], TabelaAgregados[[6]])
vecm4pib2 <- vecm4pib2 / 1000000

Anos <- seq(2003, 2023, by = 1)

tabeladiv2 <- tibble(Anos = dates, "M1/PIB" = vecm1pib2, "M2/PIB" = vecm2pib2, "M3/PIB" = vecm3pib2, "M4/PIB" = vecm4pib2)

tabeladiv2 <- tabeladiv2 %>%
  slice(150:161)

P21 <- plot_ly() %>%
  add_lines(data = tabeladiv2, x = ~Anos, y = ~`M1/PIB`, name = "M1/PIB", color = I("lawngreen")) %>%
  add_lines(data = tabeladiv2, x = ~Anos, y = ~`M2/PIB`, name = "M2/PIB", color = I("green")) %>%
  add_lines(data = tabeladiv2, x = ~Anos, y = ~`M3/PIB`, name = "M3/PIB", color = I("yellow")) %>%
  add_lines(data = tabeladiv2, x = ~Anos, y = ~`M4/PIB`, name = "M4/PIB", color = I("orange"))

P21 <- P21 %>%
  layout(
    title = "Relação dos Agregados Monetários com o PIB",
    yaxis = list(title = "Agregados Monetários (M1, M2, M3, M4)"),
      overlaying = "y",
      side = "right"
    )

P21


```

<br><br>

```{r, echo=FALSE, message=FALSE, warning=FALSE}

colnames(impcPib)[colnames(impcPib) == "Variação Percentual (%)"] <- "Variação_Percentual"
colnames(impcPib)[colnames(impcPib) == "PIB valores correntes(milhões)"] <- "PIB_Valores_Correntes_milhoes"

Plotpib2 <- plot_ly() %>%
  add_lines(data = ImpcAgre, x = ~Data, y = ~`PIB projeção`, name = "PIB (milhões)", color = I("darkblue")) %>%
  add_lines(data = Variacoes_Percentuais, x = ~Data, y = ~`PIB (%)`, name = "PIB em Variação Percentual (%)", yaxis = "y2", color = I("blue"))

# Configuração do layout com múltiplos eixos Y
Plotpib2 <- Plotpib2 %>%
  layout(
    autosize = F, # Desativa o dimensionamento automático
    width = 800,  # Largura do gráfico em pixels
    height = 600, # Altura do gráfico em pixels
    margin = list(l = 50, r = 50, b = 100, t = 100, pad = 4),
    title = "PIB e a variação nos anos próximos",
    yaxis = list(title = "PIB a valores correntes"),
    yaxis2 = list(
      title = "PIB em Variação Percentual (%)",
      overlaying = "y",
      side = "right",
      anchor = "free",
      position = 1.00
    )
  )

# Renderização do gráfico
Plotpib2


```

<br><br>





