---
title: "Untitled"
author: "Lorenzo Costa Miranda"
date: "2024-03-24"
output: html_document
---

```{r include=FALSE, message=FALSE, warning=FALSE}
library(GetBCBData)
library(dplyr)
library(pandoc)
library(ggplot2)
library(tibble)
library(tidyr)
library(kableExtra)
library(flextable)
library(openxlsx)
library(scales)
```


```{r include=FALSE, message=FALSE, warning=FALSE}
##Pegando os dados necessários pelo ID 


#reservas bancárias =/ Encaixes Totais
TabelaResBan <- GetBCBData::gbcbd_get_series(
  id =  1787,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#Papel Moeda no Poder Público

TabelaPMPP <- GetBCBData::gbcbd_get_series(
  id = 27789 ,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)


#Base monetária

TabelaBASE <- GetBCBData::gbcbd_get_series(
  id =  1788,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)


#Depósitos à vista
TabelaDepAvi <- GetBCBData::gbcbd_get_series(
 id =  27790,
 first.date = "2003-01-01",
 last.date = "2023-12-01"
)

#Meios de pagamento = PMPP + DV (TOTAL DE M1)
TabelaMP <- GetBCBData::gbcbd_get_series(
  id = 27791,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M1
TabelaM1 <- GetBCBData::gbcbd_get_series(
  id = 27791,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M2
TabelaM2 <- GetBCBData::gbcbd_get_series(
  id = 27810,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M3
TabelaM3 <- GetBCBData::gbcbd_get_series(
  id = 27813,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#M4
TabelaM4 <- GetBCBData::gbcbd_get_series(
  id = 27815,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#IPCA
TabelaIPCA <- GetBCBData::gbcbd_get_series(
  id = 433,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)

#PIB mensal a preços correntes 
TabelaPIB <- GetBCBData::gbcbd_get_series(
  id = 4380,
  first.date = "2003-01-01",
  last.date = "2023-12-01"
)
```

```{r echo = FALSE, message=FALSE, warning=FALSE}

### Criando um vetor para ser a coluna de tempo
dates <- seq.Date(from = as.Date("2003-01-01"), to = as.Date("2023-12-01"), by = "month")


#criando vetores das tabelas
vetormp <- TabelaMP[[2]]
vetordepavi <- TabelaDepAvi[[2]]
vetorresban <- TabelaResBan[[2]]
vetorPPMP <- TabelaPMPP[[2]]
vetorBASE <- TabelaBASE[[2]]
vetorM1 <- TabelaM1[[2]]
vetorM2 <- TabelaM2[[2]]
vetorM3 <- TabelaM3[[2]]
vetorM4 <- TabelaM4[[2]]
vetorIPCA <- TabelaIPCA[[2]]
vetorPIB <- TabelaPIB[[2]]


#formatando os vetores

vetor_mp <- format(vetormp, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_depavi <- format(vetordepavi, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_resban <- format(vetorresban, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_PPMP <- format(vetorPPMP, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_BASE <- format(vetorBASE, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M1 <- format(vetorM1, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M2 <- format(vetorM2, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M3 <- format(vetorM3, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_M4 <- format(vetorM4, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_IPCA <- format(vetorIPCA, big.mark = ".", decimal.mark = ",", scientific = FALSE)
vetor_PIB <-format(vetorPIB, big.mark = ".", decimal.mark = ",", scientific = FALSE)



```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#criação das séries temporais

###SABEMOS QUE B = PMPP + ENCAIXES TOTAIS / LOGO ENCAIXES TOTAIS = B - PMPP

#Função de subtração

Z <- function(s, t){
      Resultado = s - t
      return(Resultado)
}


#criando um vetor com os encaixes técnicos

VetorEncaixe <- mapply(Z, TabelaBASE[[2]], TabelaPMPP[[2]])

#Tabela do vetor de encaxe

TabelaEncaixe <- tibble(Data = dates, Valor = VetorEncaixe)

#Formatando o vetor_encaixe

Vetor_Encaixe <- format(VetorEncaixe, big.mark = ".", decimal.mark = ",", scientific = FALSE)


### juntando todas as variáveis em uma tabela só

TabelaBacen <- tibble(Data = dates, "Meios de Pagamentos" = vetor_mp, 
            "Depositos a vista" = vetor_depavi, "Encaixes Totais" = Vetor_Encaixe)




# Criando função para realizar o cálculo do coeficiente
X <- function(x,y){
  Resultado = x/y
  return(Resultado)
}



Coeficiente_e <- mapply(X, TabelaEncaixe[[2]], TabelaDepAvi[[2]])

Coeficiente_d <- mapply(X, TabelaDepAvi[,2], TabelaMP[,2])


SerieTemporal_e <- tibble(data = dates, valor = Coeficiente_e)
SerieTemporal_d <- tibble(data = dates, valor = Coeficiente_d)

y <- function(d,e){
  Resultado = 1/(1-d * (1-e))
  return(Resultado)
}

Coeficientes <- tibble(data = dates, Valor_de_e = Coeficiente_e, Valor_de_d = Coeficiente_d)


Multiplicador_mon <- mapply(y, Coeficientes[,3], Coeficientes[,2])
SerieTemporal_alpha <- tibble(data = dates, valor = Multiplicador_mon)


```


```{r echo=FALSE, message=FALSE, warning=FALSE}

TabelaBacen <- TabelaBacen %>%
  add_column(e = Coeficiente_e, d = Coeficiente_d, alpha = Multiplicador_mon, .after = "Encaixes Totais", .name_repair = "unique")

kable(TabelaBacen, format = "html", longtable = TRUE, booktabs = TRUE, caption = "Valores das Variáveis no Tempo") %>%
  kable_styling(latex_options = c("striped", "scale_down"), full_width = FALSE, font_size = 10)


```

\newpage

```{r echo=FALSE, fig.cap = "Plot da Série Temporal do Coeficiente \"e\"", fig.pos = 'H'}

ggplot(data = SerieTemporal_e) +
       aes(x = data, y = valor) +
       geom_line(colour = "red") +
       labs(x = "Data", y = "Coeficiente 'e'") +
       geom_point(colour = "black") +
  theme_minimal()

```

```{r echo=FALSE, fig.cap = "Plot da Série Temporal do Coeficiente \"d\""}

ggplot(data = SerieTemporal_d) +
  aes(x = data, y = valor) +
  geom_line(colour = "blue") +
  labs(x = "Data", y = "Coeficiente 'd'") +
  geom_point(colour = "black") +
  theme_minimal()

```

```{r echo=FALSE, fig.cap = "Plot da Série Temporal dos Coeficientes \"e\" e \"d\""}

ggplot(data = Coeficientes) +
  aes(x = data, y = Valor_de_e, color = "Valor_de_e") +
  geom_line() +
  geom_line(aes(y = Valor_de_d, color = "Valor_de_d")) +
  labs(x = "Data", y = "Valores dos coeficientes") +
  scale_color_manual(values = c("Valor_de_e" = "red", "Valor_de_d" = "blue")) +
  theme_minimal()

```

```{r echo = FALSE, message=FALSE, warning=FALSE, error=TRUE}

ggplot(data = TabelaBacen) +
  aes(x = Data, y = e, color = "e") +
  geom_line() +
  geom_line(aes(y = d, color = "d")) +
  geom_line(aes(y = alpha, color = "alpha")) +
  labs(x = "Data", y = "Valores") +
  scale_color_manual(values = c("e" = "red", "d" = "blue", "alpha" = "purple")) +
  theme_minimal()

```
```{r echo = FALSE, fig.cap = "Plot Série Temporal do Multiplicador Monetário"}

ggplot(data = SerieTemporal_alpha, aes( x = data, y = valor)) +
  geom_line(colour = "purple") +
  labs(x = "Data", y = "alpha") +
  geom_point(colour = "black") +
  theme_minimal() 

```


```{r echo = FALSE, message=FALSE, warning=FALSE}

media_multi <- mean(Multiplicador_mon)



```


```{r echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}

media_multi <- mean(Multiplicador_mon)
mean(SerieTemporal_alpha$valor[85:139], na.rm = TRUE)

media_e <- mean(Coeficiente_e) 
media_d <- mean(Coeficiente_d)


write.xlsx(TabelaBacen, "C:/Users/Lorenzo Costa/Desktop/multiplicador/TabelaBacen em xslx/TabelaBacen.xlsx")
  
  
```